# Generated by Django 5.0.3 on 2024-05-29 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_blogpost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, default="{% url static 'css/gettyimages-1986209604-594x594.jpg' %}", upload_to='blog'),
        ),
    ]
